language: node_js
node_js:
  - "stable"
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - COGNITO_POOL_ID="eu-central-1_tVle9U0Pj"
    - COGNITO_APP_CLIENT_ID="es5skki6qdv5i574n4cqbsc8e"
script:
  - yarn lint
  - yarn test
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master